### PR TITLE
Fix the bot repeat sending messages

### PR DESCRIPTION
**Pull request by jake-baxter**
Simple fix, I'm mainly a lua person so if it looks weird it looks weird.

Forgot to add the new lines, thats why it was repeating the message as it couldnt find anything to replace.

I haven't tried this because my Visual studio is playing up, but it should in theory work?

### CODE REVIEW

**Comment by jake-baxter** [comment]
To fix this issue btw: https://github.com/Exiled-Team/DiscordIntegration/issues/107

**Comment by joker-119** [comment]
msg += split[i]
and msg += $"{split[i]}" are the same thing, and the split string will already contain a \n

**Comment by jake-baxter** [comment]
Alright, fair enough but it does seem like the logs and failing to break new lines in the logs, had a intercom event repeated in my server logs and \n seemed not to appear as all the repeated logs I've had have all been on the same line and wrap around of course when it reaches the limit for the line

**Comment by jake-baxter** [comment]
image
Not sure if this uses a different version of .NET or anything, but this doesnt seem to include the splitter

**Pull request closed without merging**
